// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

declare function require(moduleName: string): any;
declare const module: { exports: any };
declare const process: {
  env: Record<string, string | undefined>;
};

require("dotenv/config");
const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
